### ISSUE TITLE
DCS Retribution doesnt launch

### ISSUE THREAD

**Issue by KrissJot** [dcs-retribution/dcs-retribution#381]
### Affected versions

v1.3.1

### Description

I had a power outage during DCS startup with DCS Retribution active (mission started). Since then I cannot start DCS Retribution. Following error appears:

"Failed to execute script 'main' due to unhandled exception:
Traceback (most recent call last):
  File "qt_ui\main.py", line 452, in <module>
  File "qt_ui\main.py", line 446, in main
  File "qt_ui\liberation_install.py", line 76, in init
  File "game\persistency.py", line 88, in setup
  File "game\persistency.py", line 131, in save_dir
  File "game\persistency.py", line 94, in base_path
AssertionError"

I removed DCS Retribution folder from Saved Games, also downloaded clean DCS Retribution package, rebooted and error still appears.

### Save game and other files

[nofile.txt](https://github.com/user-attachments/files/16431025/nofile.txt)

**Comment by Raffson** [comment]
Have you tried removing the DCSRetribution folder from AppData/Local?

**Comment by asaincread** [comment]
I have the same error, you fixe it?

**Comment by Starfire13** [comment]
> I have the same error, you fixe it?

Others have fixed it by deleting fully and reinstalling Retribution (clear the Retribution appdata folder too).

**Comment by geofffranks** [comment]
Closing this due to inactivity + provided fixes
