### ISSUE TITLE
South Atlantic added airports preventing campaign creation

### ISSUE THREAD

**Issue by Negajoule** [dcs-retribution/dcs-retribution#95]
### Affected versions

Development build

### Test/Development build

Build #302

### Campaign name

Creating new campaign on South Atlantic

### Blue faction

n/a

### Red faction

n/a

### Modifications to default settings

Any South Atlantic campaign .miz saved with the current DCS version will fail to load due to new airfields being added and not existing in the .py files

### Description

Created a new campaign .miz and .yaml file for a campaign on South Atlantic
OR
Open any campaign .miz  on the South Atlantic map (eg. gran_polvorin.miz) in DCS Mission Editor and save the file without changing anything.

Run Retribution and attempt to start a new campaign with that South Atlantic  campaign and it will fail with the exception below:

2023-02-18 20:15:15,306 :: root :: INFO :: New Game Wizard accept
2023-02-18 20:15:15,306 :: root :: INFO :: ======================
2023-02-18 20:15:15,306 :: root :: INFO :: New campaign selected: Falklands - Operation Grabthar's Hammer
2023-02-18 20:15:15,307 :: root :: INFO :: New campaign start date: 07/13/2000
2023-02-18 20:15:15,307 :: root :: WARNING :: Campaign Falklands - Operation Grabthar's Hammer does not define any squadrons
2023-02-18 20:15:15,307 :: root :: INFO :: New campaign blue faction: USA 2005
2023-02-18 20:15:15,307 :: root :: INFO :: New campaign red faction: Russia 1990
2023-02-18 20:15:15,458 :: root :: ERROR :: Uncaught exception
Traceback (most recent call last):
  File "qt_ui\windows\newgame\QNewGameWizard.py", line 204, in accept
  File "game\campaignloader\campaign.py", line 124, in load_theater
  File "game\campaignloader\mizcampaignloader.py", line 102, in __init__
  File "dcs\mission.py", line 299, in load_file
  File "dcs\terrain\terrain.py", line 595, in load_dict
AttributeError: 'NoneType' object has no attribute 'load_from_dict'
2023-02-18 20:15:26,044 :: root :: INFO :: QT App terminated with status code : 0
2023-02-18 20:15:26,044 :: root :: INFO :: Attempt to restore original mission scripting file
2023-02-18 20:15:26,046 :: root :: INFO :: QT process exited with code : 0
2023-02-18 20:15:26,054 :: uvicorn.error :: INFO :: Shutting down

### Log file

[retribution.log](https://github.com/dcs-retribution/dcs-retribution/files/10775607/retribution.log)

**Comment by Raffson** [comment]
Thanks for reporting this, hopefully I'll be able to fix this by the end of the day 👍

**Comment by Raffson** [comment]
@Negajoule I have an idea on how to ensure save-compatibility (please correct me if I misunderstood this) but since I don't have SA, I don't have any campaigns either that need to be "migrated". Any change you can share the campaign file that's causing you trouble?

**Comment by Raffson** [comment]
I seem to have misunderstood the root cause of the issue here, but I narrowed it down to a missing airfield, not sure yet how to solve that one except for doing a new export, but in order to do that I need to have the map installed 😂
